name: arXiv Slack Notifier

on:
  schedule:
    - cron: '0 0 * * *'   # UTC 0時 = 日本時間 9時
  workflow_dispatch:       # 手動実行用

jobs:
  run-notifier:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. デバッグ: ファイル一覧を確認
      - name: List files
        run: ls -R

      # 3. Pythonセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 4. 仮想環境に依存関係をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. スクリプト実行
      - name: Run arXiv Slack notifier
        env:
          SEARCH_KEYWORDS: ${{ secrets.SEARCH_KEYWORDS }}
          SEARCH_CATEGORY: ${{ secrets.SEARCH_CATEGORY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py
